import { useBreakpointValue } from '@chakra-ui/react';
import Head from 'next/head'

export default function Home() {
  const isMobile = useBreakpointValue({ base: true, md: false }) as boolean;
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        Hello World
        <p>isMobile: {isMobile.toString()}</p>
      </main>
    </>
  )
}
